[package]
name = "slices_first_word"
version = "0.1.0"
authors = ["commanderxa <art.ostrikov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
